/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FinetuneRouteImport } from './routes/finetune'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as BenchmarksIndexRouteImport } from './routes/benchmarks.index'
import { Route as BenchmarksSlugRouteImport } from './routes/benchmarks.$slug'
import { Route as DebugCatalogRouteImport } from './routes/debug.catalog'
import { Route as DebugChartsRouteImport } from './routes/debug.charts'
import { Route as FamiliesSlugRouteImport } from './routes/families.$slug'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsSlugRouteImport } from './routes/models.$slug'
import { Route as OrganizationsSlugRouteImport } from './routes/organizations.$slug'
import { Route as RankingsIndexRouteImport } from './routes/rankings.index'
import { Route as RankingsCategoryRouteImport } from './routes/rankings.$category'
import { Route as ApiCatalogVChar123versionChar125DotjsonRouteImport } from './routes/api/catalog.v{$version}[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FinetuneRoute = FinetuneRouteImport.update({
  id: '/finetune',
  path: '/finetune',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksIndexRoute = BenchmarksIndexRouteImport.update({
  id: '/benchmarks/',
  path: '/benchmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksSlugRoute = BenchmarksSlugRouteImport.update({
  id: '/benchmarks/$slug',
  path: '/benchmarks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugCatalogRoute = DebugCatalogRouteImport.update({
  id: '/debug/catalog',
  path: '/debug/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugChartsRoute = DebugChartsRouteImport.update({
  id: '/debug/charts',
  path: '/debug/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesSlugRoute = FamiliesSlugRouteImport.update({
  id: '/families/$slug',
  path: '/families/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsSlugRoute = OrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsCategoryRoute = RankingsCategoryRouteImport.update({
  id: '/rankings/$category',
  path: '/rankings/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogVChar123versionChar125DotjsonRoute =
  ApiCatalogVChar123versionChar125DotjsonRouteImport.update({
    id: '/api/catalog/v{$version}.json',
    path: '/api/catalog/v{$version}.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/finetune': typeof FinetuneRoute
  '/hardware': typeof HardwareRoute
  '/methodology': typeof MethodologyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/benchmarks/$slug': typeof BenchmarksSlugRoute
  '/debug/catalog': typeof DebugCatalogRoute
  '/debug/charts': typeof DebugChartsRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/rankings/$category': typeof RankingsCategoryRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/catalog/v{$version}.json': typeof ApiCatalogVChar123versionChar125DotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/finetune': typeof FinetuneRoute
  '/hardware': typeof HardwareRoute
  '/methodology': typeof MethodologyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/benchmarks/$slug': typeof BenchmarksSlugRoute
  '/debug/catalog': typeof DebugCatalogRoute
  '/debug/charts': typeof DebugChartsRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/rankings/$category': typeof RankingsCategoryRoute
  '/benchmarks': typeof BenchmarksIndexRoute
  '/models': typeof ModelsIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/api/catalog/v{$version}.json': typeof ApiCatalogVChar123versionChar125DotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/finetune': typeof FinetuneRoute
  '/hardware': typeof HardwareRoute
  '/methodology': typeof MethodologyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/benchmarks/$slug': typeof BenchmarksSlugRoute
  '/debug/catalog': typeof DebugCatalogRoute
  '/debug/charts': typeof DebugChartsRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/rankings/$category': typeof RankingsCategoryRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/catalog/v{$version}.json': typeof ApiCatalogVChar123versionChar125DotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/finetune'
    | '/hardware'
    | '/methodology'
    | '/robots.txt'
    | '/saved'
    | '/search'
    | '/sitemap.xml'
    | '/timeline'
    | '/benchmarks/$slug'
    | '/debug/catalog'
    | '/debug/charts'
    | '/families/$slug'
    | '/models/$slug'
    | '/organizations/$slug'
    | '/rankings/$category'
    | '/benchmarks/'
    | '/models/'
    | '/rankings/'
    | '/api/catalog/v{$version}.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/finetune'
    | '/hardware'
    | '/methodology'
    | '/robots.txt'
    | '/saved'
    | '/search'
    | '/sitemap.xml'
    | '/timeline'
    | '/benchmarks/$slug'
    | '/debug/catalog'
    | '/debug/charts'
    | '/families/$slug'
    | '/models/$slug'
    | '/organizations/$slug'
    | '/rankings/$category'
    | '/benchmarks'
    | '/models'
    | '/rankings'
    | '/api/catalog/v{$version}.json'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/finetune'
    | '/hardware'
    | '/methodology'
    | '/robots.txt'
    | '/saved'
    | '/search'
    | '/sitemap.xml'
    | '/timeline'
    | '/benchmarks/$slug'
    | '/debug/catalog'
    | '/debug/charts'
    | '/families/$slug'
    | '/models/$slug'
    | '/organizations/$slug'
    | '/rankings/$category'
    | '/benchmarks/'
    | '/models/'
    | '/rankings/'
    | '/api/catalog/v{$version}.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  FinetuneRoute: typeof FinetuneRoute
  HardwareRoute: typeof HardwareRoute
  MethodologyRoute: typeof MethodologyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimelineRoute: typeof TimelineRoute
  BenchmarksSlugRoute: typeof BenchmarksSlugRoute
  DebugCatalogRoute: typeof DebugCatalogRoute
  DebugChartsRoute: typeof DebugChartsRoute
  FamiliesSlugRoute: typeof FamiliesSlugRoute
  ModelsSlugRoute: typeof ModelsSlugRoute
  OrganizationsSlugRoute: typeof OrganizationsSlugRoute
  RankingsCategoryRoute: typeof RankingsCategoryRoute
  BenchmarksIndexRoute: typeof BenchmarksIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ApiCatalogVChar123versionChar125DotjsonRoute: typeof ApiCatalogVChar123versionChar125DotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finetune': {
      id: '/finetune'
      path: '/finetune'
      fullPath: '/finetune'
      preLoaderRoute: typeof FinetuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/': {
      id: '/benchmarks/'
      path: '/benchmarks'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof BenchmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/$slug': {
      id: '/benchmarks/$slug'
      path: '/benchmarks/$slug'
      fullPath: '/benchmarks/$slug'
      preLoaderRoute: typeof BenchmarksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/catalog': {
      id: '/debug/catalog'
      path: '/debug/catalog'
      fullPath: '/debug/catalog'
      preLoaderRoute: typeof DebugCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/charts': {
      id: '/debug/charts'
      path: '/debug/charts'
      fullPath: '/debug/charts'
      preLoaderRoute: typeof DebugChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$slug': {
      id: '/families/$slug'
      path: '/families/$slug'
      fullPath: '/families/$slug'
      preLoaderRoute: typeof FamiliesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug': {
      id: '/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof OrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$category': {
      id: '/rankings/$category'
      path: '/rankings/$category'
      fullPath: '/rankings/$category'
      preLoaderRoute: typeof RankingsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/v{$version}.json': {
      id: '/api/catalog/v{$version}.json'
      path: '/api/catalog/v{$version}.json'
      fullPath: '/api/catalog/v{$version}.json'
      preLoaderRoute: typeof ApiCatalogVChar123versionChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  FinetuneRoute: FinetuneRoute,
  HardwareRoute: HardwareRoute,
  MethodologyRoute: MethodologyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimelineRoute: TimelineRoute,
  BenchmarksSlugRoute: BenchmarksSlugRoute,
  DebugCatalogRoute: DebugCatalogRoute,
  DebugChartsRoute: DebugChartsRoute,
  FamiliesSlugRoute: FamiliesSlugRoute,
  ModelsSlugRoute: ModelsSlugRoute,
  OrganizationsSlugRoute: OrganizationsSlugRoute,
  RankingsCategoryRoute: RankingsCategoryRoute,
  BenchmarksIndexRoute: BenchmarksIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ApiCatalogVChar123versionChar125DotjsonRoute:
    ApiCatalogVChar123versionChar125DotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
